title: Notes for dummies like me
description: > # this means to ignore newlines until "baseurl:"
  My personal notes on trading, technology and supply chain. I will try to explain concept 
  in simple and easy to digest format.
permalink: '/:title'
url: "https://dummynotes.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Himanshu Gupta # add your name
author-img: himanshu-gupta.jpg # add your photo
about-author: I am a developer, always looking to learn new things.
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: dummynotes # add your discus identifier

# Tracker
analytics: G-LYRDRDQSE8 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
